arb-dir: lib/src/core/constant/localization/translations
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.json
# output-dir: lib/src/core/gen/l10n
# synthetic-package: false
# nullable-getter: false