// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtjxiuEP_8Og8cO5EWphgkB9Y8ZRFdrs',
    appId: '1:429768253634:web:040689596b4e791fb25b5b',
    messagingSenderId: '429768253634',
    projectId: 'comment-app-d785c',
    authDomain: 'comment-app-d785c.firebaseapp.com',
    storageBucket: 'comment-app-d785c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeX8Q3jmzPDYjmKQWNZOVHJKKePvGE_nA',
    appId: '1:429768253634:android:d9a5bf996c8124d1b25b5b',
    messagingSenderId: '429768253634',
    projectId: 'comment-app-d785c',
    storageBucket: 'comment-app-d785c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKlR2iol30n-F7HhdJIkKp2s-HslEZLJc',
    appId: '1:429768253634:ios:03da72969b2febb8b25b5b',
    messagingSenderId: '429768253634',
    projectId: 'comment-app-d785c',
    storageBucket: 'comment-app-d785c.firebasestorage.app',
    iosBundleId: 'com.thousand.comentt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKlR2iol30n-F7HhdJIkKp2s-HslEZLJc',
    appId: '1:429768253634:ios:03da72969b2febb8b25b5b',
    messagingSenderId: '429768253634',
    projectId: 'comment-app-d785c',
    storageBucket: 'comment-app-d785c.firebasestorage.app',
    iosBundleId: 'com.thousand.comentt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWtjxiuEP_8Og8cO5EWphgkB9Y8ZRFdrs',
    appId: '1:429768253634:web:b179d2812cd9f828b25b5b',
    messagingSenderId: '429768253634',
    projectId: 'comment-app-d785c',
    authDomain: 'comment-app-d785c.firebaseapp.com',
    storageBucket: 'comment-app-d785c.firebasestorage.app',
  );
}
